title: Connor Wood - The Beard
email: connorwood71@gmail.com
description: Systems Software Engineer | Network Software Engineer | Open Source Contributor
baseurl: ""
url: "https://connorwood.net"
github_username:  CWood1
linkedin_username: connorwood

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed
