title: BeaR&D
email: connorwood71@gmail.com
description: Systems Software Engineer | Network Software Engineer | Open Source Contributor
baseurl: ""
url: "https://connorwood.net"
github_username:  CWood1
linkedin_username: connorwood
author: Connor Wood

disqus:
  shortname: bear-d

sass:
    style: compressed

gems:
  - jekyll-feed
  